version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - agoodkind

  - package-ecosystem: swift
    directory: /Tuist
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - agoodkind
