#!/bin/bash
set -euo pipefail

GENERATED_DIR="${DERIVED_FILE_DIR}/Generated"
TEMPLATES_DIR="${SRCROOT}/Templates"

mkdir -p "${GENERATED_DIR}"

APP_BUNDLE_ID="${APP_BUNDLE_ID:-io.goodkind.plainstickies}"
ICLOUD_CONTAINER_IDENTIFIER="${ICLOUD_CONTAINER_IDENTIFIER:-iCloud.io.goodkind.plainstickies}"
SPARKLE_FEED_URL="${SPARKLE_FEED_URL:-}"
SPARKLE_PUBLIC_ED_KEY="${SPARKLE_PUBLIC_ED_KEY:-}"
CURRENT_PROJECT_VERSION="${CURRENT_PROJECT_VERSION:-1}"
MARKETING_VERSION="${MARKETING_VERSION:-0.1.0}"

sed \
  -e "s|@@APP_BUNDLE_ID@@|${APP_BUNDLE_ID}|g" \
  -e "s|@@ICLOUD_CONTAINER_IDENTIFIER@@|${ICLOUD_CONTAINER_IDENTIFIER}|g" \
  -e "s|@@SPARKLE_FEED_URL@@|${SPARKLE_FEED_URL}|g" \
  -e "s|@@SPARKLE_PUBLIC_ED_KEY@@|${SPARKLE_PUBLIC_ED_KEY}|g" \
  -e "s|@@CURRENT_PROJECT_VERSION@@|${CURRENT_PROJECT_VERSION}|g" \
  -e "s|@@MARKETING_VERSION@@|${MARKETING_VERSION}|g" \
  "${TEMPLATES_DIR}/Config.generated.swift.template" \
  > "${GENERATED_DIR}/Config.generated.swift"

