#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE_PATH="$REPO_ROOT/Config/local.xcconfig.template"
OUTPUT_PATH="$REPO_ROOT/Config/local.xcconfig"

APP_BUNDLE_ID="${APP_BUNDLE_ID:?APP_BUNDLE_ID is required}"
ICLOUD_CONTAINER_IDENTIFIER="${ICLOUD_CONTAINER_IDENTIFIER:?ICLOUD_CONTAINER_IDENTIFIER is required}"
DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM:?DEVELOPMENT_TEAM is required}"
CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY:?CODE_SIGN_IDENTITY is required}"
MARKETING_VERSION="${MARKETING_VERSION:?MARKETING_VERSION is required}"
CURRENT_PROJECT_VERSION="${CURRENT_PROJECT_VERSION:?CURRENT_PROJECT_VERSION is required}"
SPARKLE_FEED_URL="${SPARKLE_FEED_URL:?SPARKLE_FEED_URL is required}"
SPARKLE_PUBLIC_ED_KEY="${SPARKLE_PUBLIC_ED_KEY:-}"
DMG_SIGN_IDENTITY="${DMG_SIGN_IDENTITY:?DMG_SIGN_IDENTITY is required}"

sed \
    -e "s|@@APP_BUNDLE_ID@@|${APP_BUNDLE_ID}|g" \
    -e "s|@@ICLOUD_CONTAINER_IDENTIFIER@@|${ICLOUD_CONTAINER_IDENTIFIER}|g" \
    -e "s|@@DEVELOPMENT_TEAM@@|${DEVELOPMENT_TEAM}|g" \
    -e "s|@@CODE_SIGN_IDENTITY@@|${CODE_SIGN_IDENTITY}|g" \
    -e "s|@@MARKETING_VERSION@@|${MARKETING_VERSION}|g" \
    -e "s|@@CURRENT_PROJECT_VERSION@@|${CURRENT_PROJECT_VERSION}|g" \
    -e "s|@@SPARKLE_FEED_URL@@|${SPARKLE_FEED_URL}|g" \
    -e "s|@@SPARKLE_PUBLIC_ED_KEY@@|${SPARKLE_PUBLIC_ED_KEY}|g" \
    -e "s|@@DMG_SIGN_IDENTITY@@|${DMG_SIGN_IDENTITY}|g" \
    "$TEMPLATE_PATH" > "$OUTPUT_PATH"
